//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCWebService.WCF.Client.WCFTCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFTCService.ITCService")]
    public interface ITCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCService/GetStrings", ReplyAction="http://tempuri.org/ITCService/GetStringsResponse")]
        string[] GetStrings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCService/GetStrings", ReplyAction="http://tempuri.org/ITCService/GetStringsResponse")]
        System.Threading.Tasks.Task<string[]> GetStringsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCService/DoWork", ReplyAction="http://tempuri.org/ITCService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCService/DoWork", ReplyAction="http://tempuri.org/ITCService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITCServiceChannel : TCWebService.WCF.Client.WCFTCService.ITCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCServiceClient : System.ServiceModel.ClientBase<TCWebService.WCF.Client.WCFTCService.ITCService>, TCWebService.WCF.Client.WCFTCService.ITCService {
        
        public TCServiceClient() {
        }
        
        public TCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetStrings() {
            return base.Channel.GetStrings();
        }
        
        public System.Threading.Tasks.Task<string[]> GetStringsAsync() {
            return base.Channel.GetStringsAsync();
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
